### ISSUE TITLE
Document "Define a new schema specification" unclear for docker usage

### ISSUE THREAD

**Issue by th0ger** [confluentinc/kafka-connect-datagen#140]
When running in kafa-connect-datagen in Docker and specifying `"schema.filename": "/path/to/your_schema.avsc"`, using the "the absolute path" as documented in [Define a new schema specification](https://github.com/confluentinc/kafka-connect-datagen?tab=readme-ov-file#define-a-new-schema-specification), I get the following error:
```
{"error_code":400,"message":"Connector configuration is invalid and contains the following 1 error(s):
Unable to find the schema file
```
First, the error is not searchable in github issues, because it was only pasted as a screenshot in https://github.com/confluentinc/kafka-connect-datagen/issues/22#issuecomment-616625803 (@elabbassiwidad). (Hence repeating it here.)  
Second, the solution is burried deep in the comments https://github.com/confluentinc/kafka-connect-datagen/issues/22#issuecomment-616732731 (@C0urante):

> **You must copy the schema file onto the docker container you're running, at the path used for the schema.filename property in the connector config.**

**_Example_**: With local schema file in `$PWD/my_schema.avsc`
```
datagen-config.json:
---
schema.filename": "/tmp/schemas/my_schema.avsc
```
```
docker-compose.yml:
---
  connect:
    image: localimage/kafka-connect-datagen:latest
    build:
      context: .
      dockerfile: Dockerfile
    ...
    volumes:
      - type: bind
        source: .
        target: /tmp/schemas
```

I suggest to clarify the README, since "the absolute path" is a quite misleading for docker users.
